# =============================================================================
# create_project.tcl
# Creates a Vivado 2022+ project for CRC-32/ISO-HDLC hardware test
# Target : Arty A7-100T  (xc7a100tcsg324-1)
#
# Block design topology:
#
#   JTAG-AXI ──► SmartConnect ──► axi_fifo_mm_s (TX+RX)
#                                       │  AXI_STR_TXD (AXI-S master)
#                                       ▼
#                              crc_32_iso_hdlc_d32_axis   (our RTL)
#                                       │  m_axis (AXI-S master)
#                                       ▼
#                               axi_fifo_mm_s  AXI_STR_RXD (AXI-S slave)
#
# The FIFO TX path forwards data words to the CRC slave.
# The FIFO RX path captures the single-beat CRC result.
# Both paths share one axi_fifo_mm_s instance at base address 0x44A0_0000.
#
# Usage (from Vivado Tcl console):
#   source hw_test/tcl/create_project.tcl
# =============================================================================

set script_dir [file dirname [file normalize [info script]]]
set root_dir   [file normalize [file join $script_dir ../..]]
set proj_dir   [file join $script_dir ../vivado]
set proj_name  crc_hw_test

# ── RTL source files (from sample_output — generated by crcZero) ─────────────
set src_crc       [file join $root_dir sample_output crc_32_iso_hdlc_d32.v]
set src_axis      [file join $root_dir sample_output crc_32_iso_hdlc_d32_axis.v]
set src_heartbeat [file join $script_dir ../rtl/heartbeat.v]

foreach f [list $src_crc $src_axis] {
    if {![file exists $f]} {
        error "RTL source not found: $f\nRun: crcZero --algorithm CRC-32/ISO-HDLC --data-width 32 --lang verilog --output sample_output/crc_32_iso_hdlc_d32 --axi-stream"
    }
}

# ── Create project ────────────────────────────────────────────────────────────
create_project $proj_name $proj_dir -part xc7a100tcsg324-1 -force
catch { set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project] }

# ── Add RTL sources ───────────────────────────────────────────────────────────
add_files -norecurse [list $src_crc $src_axis $src_heartbeat]
update_compile_order -fileset sources_1

# ── Add XDC constraints ───────────────────────────────────────────────────────
add_files -fileset constrs_1 -norecurse \
    [file join $script_dir ../xdc/arty_a7_100t.xdc]

# ── Create block design ───────────────────────────────────────────────────────
create_bd_design "crc_test"
open_bd_design [get_files crc_test.bd]

# Clock wizard — 100 MHz → 100 MHz (adds MMCM for clean, jitter-filtered clock)
set clk_wiz [create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz clk_wiz_0]
set_property -dict [list \
    CONFIG.PRIM_IN_FREQ             {100.000} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.000} \
    CONFIG.USE_RESET                {false}   \
    CONFIG.CLKIN1_JITTER_PS         {100.0}   \
] $clk_wiz

# Processor system reset
set rst [create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset proc_sys_reset_0]

# JTAG-AXI master (provides AXI4 access via Vivado Hardware Manager TCL)
set jtag [create_bd_cell -type ip -vlnv xilinx.com:ip:jtag_axi jtag_axi_0]

# SmartConnect — converts JTAG-AXI (AXI4) to FIFO S_AXI (AXI4-Lite)
set sc [create_bd_cell -type ip -vlnv xilinx.com:ip:smartconnect smartconnect_0]
set_property -dict [list \
    CONFIG.NUM_SI {1} \
    CONFIG.NUM_MI {1} \
] $sc

# AXI FIFO MM S — one instance, TX+RX paths, 32-bit data width
# TX (AXI_STR_TXD) → CRC slave    RX (AXI_STR_RXD) ← CRC master
# C_USE_TX_CTRL=0: packet length via TLR register (no separate control stream)
# Parameter names verified against Vivado 2025.2 (axi_fifo_mm_s v4.x)
# FIFO depth 2048: supports up to 1024-beat test packets (wrapper echoes every
# beat, so RX needs same depth as TX).  Uses ~8 BRAMs on Artix-7; adjust for
# smaller parts if needed.
set fifo [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_fifo_mm_s fifo_crc]
set_property -dict [list \
    CONFIG.C_AXI_STR_TXD_TDATA_WIDTH {32}   \
    CONFIG.C_AXI_STR_RXD_TDATA_WIDTH {32}   \
    CONFIG.C_TX_FIFO_DEPTH           {2048} \
    CONFIG.C_RX_FIFO_DEPTH           {2048} \
    CONFIG.C_USE_TX_DATA             {1}    \
    CONFIG.C_USE_RX_DATA             {1}    \
    CONFIG.C_USE_TX_CTRL             {0}    \
    CONFIG.C_HAS_AXIS_TKEEP          {false} \
    CONFIG.C_HAS_AXIS_TSTRB          {false} \
    CONFIG.C_HAS_AXIS_TDEST          {false} \
    CONFIG.C_HAS_AXIS_TUSER          {false} \
] $fifo

# CRC core — module reference (Vivado infers s_axis/m_axis interfaces from port names)
set crc [create_bd_cell -type module -reference crc_32_iso_hdlc_d32_axis crc_core]

# Heartbeat LED — blinks LD0 at ~1.5 Hz to confirm the design is alive
set hb [create_bd_cell -type module -reference heartbeat heartbeat_0]

# ── External ports ────────────────────────────────────────────────────────────
create_bd_port -dir I -type clk -freq_hz 100000000 sys_clk
create_bd_port -dir I -type rst resetn
set_property CONFIG.POLARITY ACTIVE_LOW [get_bd_ports resetn]
create_bd_port -dir O led0

# ── Clock connections ─────────────────────────────────────────────────────────
set aclk [get_bd_pins clk_wiz_0/clk_out1]

connect_bd_net [get_bd_ports sys_clk]       [get_bd_pins clk_wiz_0/clk_in1]
connect_bd_net [get_bd_pins clk_wiz_0/locked] \
               [get_bd_pins proc_sys_reset_0/dcm_locked]
connect_bd_net $aclk \
    [get_bd_pins proc_sys_reset_0/slowest_sync_clk] \
    [get_bd_pins jtag_axi_0/aclk]                   \
    [get_bd_pins smartconnect_0/aclk]                \
    [get_bd_pins fifo_crc/s_axi_aclk]               \
    [get_bd_pins crc_core/clk]                       \
    [get_bd_pins heartbeat_0/clk]

# ── Reset connections ─────────────────────────────────────────────────────────
connect_bd_net [get_bd_ports resetn] \
               [get_bd_pins proc_sys_reset_0/ext_reset_in]

connect_bd_net [get_bd_pins proc_sys_reset_0/interconnect_aresetn] \
               [get_bd_pins smartconnect_0/aresetn]

connect_bd_net [get_bd_pins proc_sys_reset_0/peripheral_aresetn] \
    [get_bd_pins jtag_axi_0/aresetn]   \
    [get_bd_pins fifo_crc/s_axi_aresetn] \
    [get_bd_pins crc_core/rst_n]         \
    [get_bd_pins heartbeat_0/rst_n]

connect_bd_net [get_bd_pins heartbeat_0/led] [get_bd_ports led0]

# ── AXI connections ───────────────────────────────────────────────────────────
connect_bd_intf_net [get_bd_intf_pins jtag_axi_0/M_AXI]    \
                    [get_bd_intf_pins smartconnect_0/S00_AXI]
connect_bd_intf_net [get_bd_intf_pins smartconnect_0/M00_AXI] \
                    [get_bd_intf_pins fifo_crc/S_AXI]

# ── AXI-Stream connections ────────────────────────────────────────────────────
# Try interface-level connections first (works when Vivado infers s_axis/m_axis
# interfaces from port names).  If validate_bd_design reports an error here,
# replace with the individual connect_bd_net calls shown in the comment below.
connect_bd_intf_net [get_bd_intf_pins fifo_crc/AXI_STR_TXD] \
                    [get_bd_intf_pins crc_core/s_axis]
connect_bd_intf_net [get_bd_intf_pins crc_core/m_axis] \
                    [get_bd_intf_pins fifo_crc/AXI_STR_RXD]

# -- Individual-signal fallback (uncomment if interface inference fails) -------
# connect_bd_net [get_bd_pins fifo_crc/AXI_STR_TXD_TDATA]  [get_bd_pins crc_core/s_axis_tdata]
# connect_bd_net [get_bd_pins fifo_crc/AXI_STR_TXD_TVALID] [get_bd_pins crc_core/s_axis_tvalid]
# connect_bd_net [get_bd_pins crc_core/s_axis_tready]       [get_bd_pins fifo_crc/AXI_STR_TXD_TREADY]
# connect_bd_net [get_bd_pins fifo_crc/AXI_STR_TXD_TLAST]  [get_bd_pins crc_core/s_axis_tlast]
# connect_bd_net [get_bd_pins crc_core/m_axis_tdata]        [get_bd_pins fifo_crc/AXI_STR_RXD_TDATA]
# connect_bd_net [get_bd_pins crc_core/m_axis_tvalid]       [get_bd_pins fifo_crc/AXI_STR_RXD_TVALID]
# connect_bd_net [get_bd_pins fifo_crc/AXI_STR_RXD_TREADY] [get_bd_pins crc_core/m_axis_tready]
# connect_bd_net [get_bd_pins crc_core/m_axis_tlast]        [get_bd_pins fifo_crc/AXI_STR_RXD_TLAST]
# -----------------------------------------------------------------------------

# ── Address assignment ────────────────────────────────────────────────────────
assign_bd_address [get_bd_addr_segs {fifo_crc/S_AXI/Mem0}]
set_property offset 0x44A00000 \
    [get_bd_addr_segs {jtag_axi_0/Data/SEG_fifo_crc_Mem0}]
set_property range 64K \
    [get_bd_addr_segs {jtag_axi_0/Data/SEG_fifo_crc_Mem0}]

# ── Validate, save, wrap ──────────────────────────────────────────────────────
validate_bd_design
save_bd_design

make_wrapper -files [get_files crc_test.bd] -top
# In Vivado 2023+, generated files land in .gen/ not .srcs/
set wrapper [lindex [glob \
    [file join $proj_dir ${proj_name}.gen  sources_1 bd crc_test hdl crc_test_wrapper.v] \
    [file join $proj_dir ${proj_name}.srcs sources_1 bd crc_test hdl crc_test_wrapper.v] \
    ] 0]
add_files -norecurse $wrapper
set_property top crc_test_wrapper [current_fileset]
update_compile_order -fileset sources_1

puts ""
puts "Block design ready."
puts "Next: source hw_test/tcl/run_impl.tcl"
